'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.18408
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Projeto_Sons.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alarme() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alarme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlarmeIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlarmeIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Aplausos() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Aplausos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AplausosIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AplausosIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property assobioIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assobioIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Assovio() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Assovio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Bomba() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Bomba", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bombaIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bombaIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property CAMERA() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("CAMERA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cameraIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cameraIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Campainha() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Campainha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CampainhaIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CampainhaIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Dinheiro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Dinheiro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DinheiroIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DinheiroIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Drama() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Drama", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DramaIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DramaIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Espirro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Espirro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EspirrroIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EspirrroIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mágica() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mágica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MágicaIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MágicaIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mensagem() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mensagem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MensagemIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MensagemIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Tosse() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Tosse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tosseIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tosseIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrompeteIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrompeteIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Trumpete() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Trumpete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.IO.UnmanagedMemoryStream semelhante a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Vaiar() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Vaiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VaiarIMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VaiarIMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
